### ISSUE TITLE
dialog resized with keeping scrollbar

### ISSUE THREAD

**Issue by MykolaGalian** [BrightspaceUI/core#946] opened 2020-11-12 09:28 UTC
Now we using the `resize()` method when showing a list of default courses on the `d2l-dialog` window.
[Example](https://github.com/Brightspace/insights-engagement-dashboard/blob/7ae47619f65b2f7b7e3235b3c8f63fd9ae8e7db3/components/default-view-popup.js#L107), [Defect](https://rally1.rallydev.com/#/detail/defect/444478190640).
But in this case, we have a scrollbar. Seems odd that `d2l-dialog` has a scrollbar when the list is showing everything in view. The scrollbar appears after pressing the `d2l-expand-collapse-content` component button, and apparently, the `resize()` can't remove the scrollbar.

The expected behavior is a scrollbar appear if the `d2l-dialog` height exceeds the maximum specified height.

![dialog](https://user-images.githubusercontent.com/27500223/98921412-f01f0500-24d9-11eb-96a9-bcd7d3f1362a.gif)
![2](https://user-images.githubusercontent.com/27500223/98921503-0fb62d80-24da-11eb-82f5-02c048cc7a99.jpg)

With the `setTimeOut` for `resize()` method, it looks like this:
![12](https://user-images.githubusercontent.com/27500223/98925351-8ce3a180-24de-11eb-8bbf-dd7aa5373ab2.gif)

**Comment by dbatiste** [comment] 2020-11-12 13:43
Is there any chance there is some margin in play here.  For example, margin at the very top, or the very bottom of the content?  I think this scenario arise in that particular case.  We can look at ways to account for that, but need some more info.

**Comment by MykolaGalian** [comment] 2020-11-12 13:54
Here is the code where we use the `d2l-dialog` https://github.com/Brightspace/insights-engagement-dashboard/blob/7ae47619f65b2f7b7e3235b3c8f63fd9ae8e7db3/components/default-view-popup.js#L24. And you can see that the margin is 0. But maybe I'm missing something

**Comment by dbatiste** [comment] 2020-11-12 14:12
Is there a place I can go to see this in action, where I can inspect the DOM, etc.?  I am unable to reproduce this in the demo pages.

**Comment by MykolaGalian** [comment] 2020-11-12 14:15
Yes, we have demo page:  https://github.com/Brightspace/insights-engagement-dashboard/blob/7ae47619f65b2f7b7e3235b3c8f63fd9ae8e7db3/demo/index.html  Popup window with d2l-dialog appears immediately on page load

**Comment by MykolaGalian** [comment] 2020-11-12 14:37
I'm not sure if this will work easily, besides the demo page

**Comment by dlockhart** [comment] 2020-11-12 16:03
Updating this issue as @MykolaGalian and I met and he shared his screen with me:

So far only Mykola can reproduce this (we think) and only in Chrome on Windows although earlier it was reproducible in other browsers for him but not anymore. Mykola is going to check with his team (@bemailloux maybe you've seen this?) and get back to us if there's a common setup that causes it. Maybe it's a page zoom setting, a browser plugin, an OS setting, or an animation setting.

@dbatiste, @svanherk and I cannot reproduce this in the demo page for the Engagement Dashboard or in the LMS in any Chrome/Firefox/Safari/Edge on Mac or Windows.

**Comment by bemailloux** [comment] 2020-11-12 16:10
> Updating this issue as @MykolaGalian and I met and he shared his screen with me:
> 
> So far only Mykola can reproduce this (we think) and only in Chrome on Windows although earlier it was reproducible in other browsers for him but not anymore. Mykola is going to check with his team (@bemailloux maybe you've seen this?) and get back to us if there's a common setup that causes it. Maybe it's a page zoom setting, a browser plugin, an OS setting, or an animation setting.
> 
> @dbatiste, @svanherk and I cannot reproduce this in the demo page for the Engagement Dashboard or in the LMS in any Chrome/Firefox/Safari/Edge on Mac or Windows.

I am able to reproduce this consistently in Chrome, Firefox, Edgium and Edge Legacy on Windows.

**Comment by MykolaGalian** [comment] 2020-11-12 16:14
Yes, it shows up when the page size is less than 100% for me

**Comment by dlockhart** [comment] 2020-11-12 16:21
Alright, I'm going to close this issue for now until we determine that it's more widespread than just Mykola's machine and get some consistent reproduction steps. Feel free to re-open if that happens.

**Closed by dlockhart** 2020-11-12 16:21 UTC

**Comment by svanherk** [comment] 2020-11-12 17:26
> Yes, it shows up when the page size is less than 100% for me

That did it for me too!  Windows on Chrome, browser zoom 90%
