### ISSUE TITLE
Use Radio Icon for d2l-menu-item-radio Instead of Check Mark

### ISSUE THREAD

**Issue by Jevan5** [BrightspaceUI/core#858] opened 2020-09-18 20:05 UTC
# Use Radio Icon for d2l-menu-item-radio Instead of Check Mark
## What do we want to do?
Use radio icons for `<d2l-menu-item-radio>` elements, instead of the check mark.

![Playback Speed](https://user-images.githubusercontent.com/24978103/93640160-1cca0b00-f9c8-11ea-96b1-cc22db1688fd.jpg)

## Why do we want to do this?
Multiple selection menus are typically designed using checkmarks ([examples](https://www.google.com/search?q=multiple+selection+menu&sxsrf=ALeKk02U2zu-uduPgwzqWhjl1L8Hzb-sfA:1600459373408&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiBorfjv_PrAhUFHM0KHZZ9AeUQ_AUoAXoECA8QAw&biw=892&bih=939)), while radio selections are typically designed using radio buttons ([examples](https://www.google.com/search?q=radio+selection+menu&tbm=isch&ved=2ahUKEwil5Z_kv_PrAhXVMs0KHZCFAE4Q2-cCegQIABAA&oq=radio+selection+menu&gs_lcp=CgNpbWcQAzIECCMQJ1Dy-wNYlf4DYK6ABGgAcAB4AIABSogBxwKSAQE1mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=bxJlX-XxBtXltAaQi4LwBA&bih=939&biw=892)). To make it more clear to the user what kind of menu they are interacting with, the `<d2l-menu-item-radio>` elements should use radio buttons instead of check marks.

**Comment by dbatiste** [comment] 2020-09-18 20:19
The checkmark for the radio menu items was by design.  If we want to change this, or alter the API of the component to support different rendering, we'll need to run by Design.  FYI: @geurts

**Comment by Jevan5** [comment] 2020-09-21 20:33
I instead used the MenuItemRadioMixin to implement my own MenuItemRadio component, because I have much more CSS that I want to customize as well. From there, I can replace the icons that are displayed

**Comment by dlockhart** [comment] 2020-10-01 14:56
Closing, as design has decided that checkmarks are OK.

**Closed by dlockhart** 2020-10-01 14:56 UTC
Labels: enhancement
